// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmc_-1t2IydD5fT8dr1D8G0Yy9bxmnC3w',
    appId: '1:389404943176:web:d4b561e7c3d507140c497d',
    messagingSenderId: '389404943176',
    projectId: 'fluttergram-c1140',
    authDomain: 'fluttergram-c1140.firebaseapp.com',
    storageBucket: 'fluttergram-c1140.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1FSlqk8j2gtz1eEtZ7NIA1CeQ_ZH2ys',
    appId: '1:389404943176:android:6f39a4731649ea160c497d',
    messagingSenderId: '389404943176',
    projectId: 'fluttergram-c1140',
    storageBucket: 'fluttergram-c1140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4R60PrF6_lrzGef0Vxr7CLMFfKT4az8',
    appId: '1:389404943176:ios:8331685b7b6ee1ae0c497d',
    messagingSenderId: '389404943176',
    projectId: 'fluttergram-c1140',
    storageBucket: 'fluttergram-c1140.appspot.com',
    iosBundleId: 'com.directions.istagram.instagram',
  );
}
