name: instagram
description: clone instagram
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^0.13.4

    cupertino_icons: ^1.0.2
    image_picker: ^0.8.4+4
    change_app_package_name: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    firebase_core: ^2.16.0
    firebase_auth: ^4.9.0
    cloud_firestore: ^4.9.0
    provider: ^6.0.5

flutter:
    uses-material-design: true

    assets:
        - assets/
